### ISSUE TITLE
get Malone code to run

### ISSUE THREAD

**Issue by bogsnork** [naturalengland/EPM_samp_strat#2]
Malone code should be running on a subset of the data with low iterations just to demonstrate outputs

**Comment by bogsnork** [comment]
as discussed: 

- [ ] create a smaller test area
- [ ] get the code running with sensible outputs
- [ ] discuss
- [ ] then test on full area

**Comment by Daveron-S** [comment]
A couple of issues to fix:

 - [ ] some of the covs are factors currently treated as num

- [ ]  check column numbers in row 69 and 81

**Comment by bogsnork** [comment]
First thing: code should be in the R folder, currently in Project base directory with a further copy in R!!  I'll move it at the end otherwise things will get confusing.

**Comment by bogsnork** [comment]
Code currently falls over here: 
https://github.com/naturalengland/EPM_samp_strat/blob/30abc5913c733d8a1f4f766f1a65c770dcc38def/R/Mod_Malone_Code.R#L84-L89
With error message: 
`Error in Summary.factor(c(5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L, 5L,  : 
  ‘max’ not meaningful for factors`

**Comment by Daveron-S** [comment]
Ah! Of course, factor covariates are going to be a problem when calculating quantiles, any ideas on how to solve that?

**Comment by bogsnork** [comment]
have been reading around, but not finding an obvious solution.

**Comment by bogsnork** [comment]
Best I've got so far is to split the superficial geology classes into separate variables with a coverage value.  I'm going to have to park code review there for the time being.  Have resurrected the branch.

**Comment by bogsnork** [comment]
Or we park KL completely and use the ordination based metric where we're not going to have issues with categorical variables in theory.
