### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by bogsnork** [naturalengland/EPM_samp_strat#21]

**Comment by bogsnork** [comment]
- in readme.md add table showing which covar files required and naming conventions
-

**Comment by bogsnork** [comment]
the code itself is working really well.  Have re-written this mainly to make all paths relative to the project directory and to make input and output directories variables set by the user.  Have run it on real data and on the test data: with the test data we're getting CRS error above. 

Now needs some documentation, most urgently for what inputs data is expected.

**Comment by Daveron-S** [comment]
> CRS error
> in
> 
> https://github.com/naturalengland/EPM_samp_strat/blob/667be82fbe4765b5fdf3bcd36a3244d07e1fa011/R/cLHSwithKLDivergence.R#L676-L677
> 
> getting error: `Error in CRS("+init=epsg:27700") : NA`
> @Daveron-S any ideas?

Working for me, you could specify the package and the full proj4string, so:

SPsamplepoints <-
    sp::SpatialPoints(samplepoints[1:2], proj4string = CRS("+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs"))

**Comment by bogsnork** [comment]
Yup, full proj4string worked, no idea why... specifying the package made no diff.   Thanks!
fixed in c1a21df

> Working for me, you could specify the package and the full proj4string, so:
> 
> SPsamplepoints <-
> sp::SpatialPoints(samplepoints[1:2], proj4string = CRS("+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs"))

**Comment by bogsnork** [comment]
I've tested this on SCE now and aside from issues with package installs, it runs cleanly on the test data.
