### ISSUE TITLE
sample size loop `break` condition

### ISSUE THREAD

**Issue by bogsnork** [naturalengland/EPM_samp_strat#22]
@Daveron-S , please help!  I don't understand this code. I think it tests for when to break the internal loop in the sample size calculation but I don't understand why its checking for duplicate rows.  

https://github.com/naturalengland/EPM_samp_strat/blob/fb349c406f25aef92ccddb6fc92607ed2c5e5df9/R/cLHSwithKLDivergence.R#L351-L352

**Comment by Daveron-S** [comment]
Ah, yes - this is from the original code, my understanding is that he's checking that it isn't throwing up duplicated sample points (i.e. telling you to sample at the same pixel twice). I believe this is just a backstop for much smaller areas with a higher density of sample points. Practically irrelevant to our purposes, but also causing no harm so I didn't remove it.
